const quotes = [
  "*The only way to do great work is to love what you do. – Steve Jobs*", 
  "*Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau*", 
  "*Opportunities don't happen. You create them. – Chris Grosser*", 
  "*The best revenge is massive success. – Frank Sinatra*", 
  "*Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill*", 
  "*Believe you can and you're halfway there. – Theodore Roosevelt*", 
  "*The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt*", 
  "*It does not matter how slowly you go as long as you do not stop. – Confucius*", 
  "*You miss 100% of the shots you don't take. – Wayne Gretzky*", 
  "*Act as if what you do makes a difference. It does. – William James*", 
  "*Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett*", 
  "*Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis*", 
  "Your time is limited, don't waste it living someone else's life. – Steve Jobs", 
  "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt", 
  "You have within you right now, everything you need to deal with whatever the world can throw at you. – Brian Tracy", 
  "The best way to predict your future is to create it. – Peter Drucker", 
  "In the middle of every difficulty lies opportunity. – Albert Einstein", 
  "The harder you work for something, the greater you’ll feel when you achieve it. – Unknown", 
  "Dream it. Believe it. Build it. – Unknown", 
  "Don’t watch the clock; do what it does. Keep going. – Sam Levenson", 
  "Everything you’ve ever wanted is on the other side of fear. – George Addair", 
  "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt", 
  "Success is not in what you have, but who you are. – Bo Bennett", 
  "The journey of a thousand miles begins with one step.– Lao Tzu", 
  "It always seems impossible until it’s done. – Nelson Mandela", 
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis", 
  "Do what you can, with what you have, where you are. – Theodore Roosevelt", 
  "Start where you are. Use what you have. Do what you can. – Arthur Ashe", 
  "Success is not just about making money. It’s about making a difference. – Unknown", 
  "Your limitation—it’s only your imagination. – Unknown", 
  "Push yourself, because no one else is going to do it for you. – Unknown", 
  "Great things never come from comfort zones. – Unknown", 
  "Dream it. Wish it. Do it. – Unknown", 
  "Success doesn’t just find you. You have to go out and get it. – Unknown", 
  "The harder you work, the more successful you’ll be. – Unknown", 
  "Dream bigger. Do bigger. – Unknown", 
  "Don’t stop when you’re tired. Stop when you’re done. – Unknown", 
  "Wake up with determination. Go to bed with satisfaction. – Unknown", 
  "Push yourself, because no one else is going to do it for you. – Unknown", 
  "Great things never come from comfort zones. – Unknown", 
  "Dream it. Wish it. Do it. – Unknown", 
  "Success doesn’t just find you. You have to go out and get it. – Unknown", 
  "The harder you work, the more successful you’ll be. – Unknown", 
  "Dream bigger. Do bigger. – Unknown", 
  "Don’t stop when you’re tired. Stop when you’re done. – Unknown", 
  "Wake up with determination. Go to bed with satisfaction. – Unknown", 
  "The key to success is to focus on goals, not obstacles. – Unknown", 
  "Dream it. Believe it. Chase it. – Unknown", 
  "Success is a journey, not a destination. – Unknown", 
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett", 
];

const handleMotivationalQuote = async (sock, from, message) => {
  const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
  await sock.sendMessage(from, { text: randomQuote }, { quoted: message });
};

module.exports = handleMotivationalQuote;
